FROM rust:alpine

RUN apk add --no-cache \
    libc-dev \
    gcc \
    make \
    bash

WORKDIR /app
COPY . .

# Run only tests to verify OS/libc specifics
CMD ["bash", "-c", "cargo test && ./tests/shell_test.sh ./target/debug/asleep"]
